version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    command: sh -c "yarn install && yarn build && yarn start"
    # depends_on:
    #   - mongo
    environment: -DATABASE_URI
      -PAYLOAD_SECRET
      -NEXT_PUBLIC_SERVER_URL
      -CRON_SECRET
      -S3_BUCKET_NAME
      -S3_ACCESS_KEY
      -S3_SECRET_KEY
      -S3_ENDPOINT
      -S3_REGION

volumes:
  node_modules:
