name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-name:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-name:${{ github.sha }}
          build-args: [
            PAYLOAD_SECRET=${{secrets.PAYLOAD_SECRET}},
            DATABASE_URI=${{secrets.DATABASE_URI}},
            CRON_SECRET=${{secrets.CRON_SECRET}},
            S3_BUCKET_NAME=${{secrets.S3_BUCKET_NAME}},
            S3_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}},
            S3_SECRET_KEY=${{secrets.S3_SECRET_KEY}},
            S3_ENDPOINT=${{secrets.S3_ENDPOINT}} ]
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-name:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-name:buildcache,mode=max
